import { marketplaceUi } from "@/lib/marketplace-ui";

export default {
  light: {
    text: marketplaceUi.colors.text,
    textSecondary: marketplaceUi.colors.textSecondary,
    textMuted: marketplaceUi.colors.textMuted,
    productTitle: marketplaceUi.colors.productTitle,
    background: marketplaceUi.colors.background,
    surface: marketplaceUi.colors.surface,
    header: marketplaceUi.colors.header,
    tint: marketplaceUi.colors.primary,
    price: marketplaceUi.colors.price,
    discount: marketplaceUi.colors.discount,
    cartButton: marketplaceUi.colors.cartButton,
    featured: marketplaceUi.colors.featured,
    tabIconDefault: marketplaceUi.colors.textMuted,
    tabIconSelected: marketplaceUi.colors.primary,
    border: marketplaceUi.colors.border,
    promotional: marketplaceUi.colors.promotional,
    error: marketplaceUi.colors.error,
    primaryLight: marketplaceUi.colors.primaryLight,
    freeShip: marketplaceUi.colors.freeShip,
    mall: marketplaceUi.colors.mall,
    star: marketplaceUi.colors.star,
  },
  dark: {
    text: marketplaceUi.colors.text,
    textSecondary: marketplaceUi.colors.textSecondary,
    textMuted: marketplaceUi.colors.textMuted,
    productTitle: marketplaceUi.colors.productTitle,
    background: marketplaceUi.colors.background,
    surface: marketplaceUi.colors.surface,
    header: marketplaceUi.colors.header,
    tint: marketplaceUi.colors.primary,
    price: marketplaceUi.colors.price,
    discount: marketplaceUi.colors.discount,
    cartButton: marketplaceUi.colors.cartButton,
    featured: marketplaceUi.colors.featured,
    tabIconDefault: marketplaceUi.colors.textMuted,
    tabIconSelected: marketplaceUi.colors.primary,
    border: marketplaceUi.colors.border,
    promotional: marketplaceUi.colors.promotional,
    error: marketplaceUi.colors.error,
    primaryLight: marketplaceUi.colors.primaryLight,
    freeShip: marketplaceUi.colors.freeShip,
    mall: marketplaceUi.colors.mall,
    star: marketplaceUi.colors.star,
  },
};
